[package]
name = "coach"
version = "0.1.0"
authors = ["Brian Schwind <brianmschwind@gmail.com>"]
edition = "2018"

[dependencies]
rs-frame = { path = "../rs-frame" }
regex = "1.1.6"
serde = { version = "1.0", features = ["derive"] }
serde_qs = "0.4.5"
