[package]
name = "coach"
version = "0.1.0"
authors = ["Brian Schwind <brianmschwind@gmail.com>"]
edition = "2018"

[dependencies]
rs-frame = { path = "../rs-frame" }
rs-frame-macros = { path = "../rs-frame-macros" }
regex = "1.1.6"
